# Protobuf files lint and backwards compatibility check job
# reference: <https://docs.buf.build/ci-cd/github-actions>
name: protobuf-check

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  protobuf-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1
      - run: buf format --diff --exit-code
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Test protobuf changes generates new go files
        run: |
          export PATH="$PATH:$(go env GOPATH)/bin"
          go install github.com/cosmos/gogoproto/protoc-gen-gocosmos
          go install github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
          make proto-gen-check
